name: Milestone
version: ${version}
main: com.github.cinnaio.milestone.Milestone
api-version: '1.21'
folia-supported: true
authors: [Cinnaio]
depend: [ProtocolLib]
description: A server-grade achievement system.
commands:
  milestone:
    description: Main command for Milestone
    usage: /milestone <subcommand>
    permission: milestone.use
    aliases: [mls]
permissions:
  milestone.admin:
    description: Admin permission for Milestone
    default: op
